name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: '1492949083'
        reponame: 'VueTest'
        cname: 'vue.766677.xyz'
        token: ${{ secrets.PAT }} # Leave this line unchanged
